apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Release.Name }}
      tier: app
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Release.Name }}
        tier: app
        date: "{{ .Release.Time.Seconds }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}-{{ .Release.Name }}
          image: "registry.ng.bluemix.net/nicedoc/nicedoc:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /api/status
              port: http
          readinessProbe:
            httpGet:
              path: /api/status
              port: http
          env:
            - name: GITHUB_TOKEN
              value: "{{ .Values.env.GITHUB_TOKEN }}"
            - name: SITE_URL
              value: "https://nicedoc.io"
      imagePullSecrets:
        - name: regcred
